/* Services reported by the log stream — single source for the logs filter. */
export const LOG_SERVICE_OPTIONS = [
  'all',
  'api-gateway',
  'monitoring-service',
  'conversation-service',
  'call-service',
  'auth-service',
  'user-service',
  'friend-service',
  'notification-service',
  'content-service',
  'media-service',
  'media-processing-service',
  'media-processing-long-service',
  'reel-indexing-service',
  'reel-indexing-long-service',
  'payment-service',
  'mail-service',
  'ai-service',
  'nginx',
  'rabbitmq',
  'prometheus',
  'node-exporter',
  'grafana',
  'loki',
  'alloy',
] as const
